-- Generated by nwg-displays on 2026-06-22 at 20:56:03. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    mirror = "eDP-1"
})
